export const USERS = [
    {
        name: '홍길동',
        id: 'abcd123',
        email: 'hong@korea.com',
        auth: 'admin',
        createAt: '2024.07.23',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
    {
        name: '김영수',
        id: 'fjkdie',
        email: 'kim@korea.com',
        auth: 'normal',
        createAt: '2024.06.22',
    },
    {
        name: '박영희',
        id: 'park',
        email: 'park@korea.com',
        auth: 'normal',
        createAt: '2024.05.11',
    },
]