import { EditorConfig } from "ckeditor5";
import {
    Bold,
    Essentials,
    Italic,
    Mention,
    Paragraph,
    Undo,
    Underline,
    Strikethrough,
    Subscript,
    Superscript,
    Font,
    Heading,
    List,
    Link,
    Image,
    ImageUpload,
    SimpleUploadAdapter,
    FileRepository,
    MediaEmbed,
    Table,
    BlockQuote,
    CodeBlock,
    HorizontalLine,
    PageBreak,
    SpecialCharacters,
    SourceEditing,
    Alignment,
} from 'ckeditor5';
// import useCKEditorExtraPlugin from "./useCKEditorExtraPlugin";

export const config: EditorConfig = {
    language: 'ko',
    initialData: '',
    plugins: [
        Bold,
        Essentials,
        Italic,
        // Mention,
        Paragraph,
        Undo,
        Underline,
        Strikethrough,
        // Subscript,
        // Superscript,
        Font,
        Heading,
        List,
        Link,
        Image,
        ImageUpload,
        // SimpleUploadAdapter,
        // FileRepository,
        // MediaEmbed,
        Table,
        // BlockQuote,
        CodeBlock,
        HorizontalLine,
        // PageBreak,
        // SpecialCharacters,
        // SourceEditing,
        Alignment,
    ],
    // extraPlugins: [ useCKEditorExtraPlugin ],
    toolbar: {
        items: [
            'undo',
            'redo',
            '|',
            'heading',
            '|',
            'bold',
            'italic',
            'underline',
            'strikethrough',
            // 'subscript',
            // 'superscript',
            'fontColor',
            // 'fontBackgroundColor',
            'fontSize',
            // 'fontFamily',
            '|',
            'alignment',
            'bulletedList',
            'numberedList',
            // 'indent',
            // 'outdent',
            '|',
            'link',
            'imageUpload',
            // 'mediaEmbed',
            'insertTable',
            // 'blockQuote',
            'codeBlock',
            'horizontalLine',
            // 'pageBreak',
            // 'specialCharacters',
            // 'sourceEditing',
        ],
        shouldNotGroupWhenFull: true,
    },
}