export const BEST_PREDICT_MODEL_LIST = 'BEST_PREDICT_MODEL_LIST';
export const PREDICT_MODEL_LIST = 'PREDICT_MODEL_LIST';


export const MODEL_DETAIL = 'MODEL_DETAIL';
export const MODEL_DETAIL_RECENT_BEST = 'MODEL_DETAIL_RECENT_BEST';
export const MODEL_DETAIL_SIGN_LIST = 'MODEL_DETAIL_SIGN_LIST';


export const CRYPTO_DETAIL_SIGN_LIST = 'CRYPTO_DETAIL_SIGN_LIST';
export const CRYPTO_DETAIL_TIMELINE = 'CRYPTO_DETAIL_TIMELINE';


export const CRYPTO_DETAIL_INFO = 'CRYPTO_DETAIL_INFO';


export const DISCOVER_CHART = 'DISCOVER_CHART';
export const COPY_TRADING_INFO = 'COPY_TRADING_INFO';


export const HOME_SIGN_ID_LIST = 'HOME_SIGN_ID_LIST';
export const HOME_SIGN_ITEMS = 'HOME_SIGN_ITEMS';
export const HOME_CRYPTO_FILTER_LIST = 'HOME_CRYPTO_FILTER_LIST';


export const PERSONA_NEWS_REPORTERS = 'PERSONA_NEWS_REPORTERS';
export const PERSONA_NEWS_REPORTER_DESCRIPTION = 'PERSONA_NEWS_REPORTER_DESCRIPTION';
export const PERSONA_NEWS_LIST = 'PERSONA_NEWS_LIST';
export const PERSONA_NEWS_CHAT_LIST = 'PERSONA_NEWS_CHAT_LIST';


export const ALL_CRYPTO_LIST = 'ALL_CRYPTO_LIST';


export const SIGN_DETAIL_PROFILE = 'SIGN_DETAIL_PROFILE';
export const SIGN_DETAIL_RECENT_SIGNLIST = 'SIGN_DETAIL_RECENT_SIGNLIST';
export const SIGN_DETAIL_CONTENT = 'SIGN_DETAIL_CONTENT';


export const MENU_USER_INFO = 'MENU_USER_INFO';


export const CUSTOMER_FAQ_LATEST_LIST = 'CUSTOMER_FAQ_LATEST_LIST';
export const CUSTOMER_NOTICE_LIST = 'CUSTOMER_NOTICE_LIST';
export const CUSTOMER_NOTICE_DETAIL = 'CUSTOMER_NOTICE_DETAIL';
export const CUSTOMER_MY_QNA = 'CUSTOMER_MY_QNA';


export const CHAT_GET_ROOM = 'CHAT_GET_ROOM';
export const CHAT_GET_USER = 'CHAT_GET_USER';
export const CHAT_GET_HISTORY = 'CHAT_GET_HISTORY';